name: 'Circular Dependency Hunter'
description: 'Find circular dependencies in your codebase using Supermodel graphs'
author: 'Supermodel Tools'

branding:
  icon: 'search'
  color: 'red'

inputs:
  supermodel-api-key:
    description: 'Supermodel API key from https://supermodeltools.com'
    required: true
  github-token:
    description: 'GitHub token for posting PR comments (defaults to github.token)'
    required: false
    default: ${{ github.token }}
  comment-on-pr:
    description: 'Post findings as PR comment'
    required: false
    default: 'true'
  fail-on-circular-deps:
    description: 'Fail the action if circular dependencies are found'
    required: false
    default: 'false'
  ignore-patterns:
    description: 'JSON array of glob patterns to ignore'
    required: false
    default: '[]'
  debug:
    description: 'Log graph diagnostics for debugging'
    required: false
    default: 'false'

outputs:
  circular-dependency-count:
    description: 'Number of circular dependencies found'
  circular-dependency-json:
    description: 'JSON array of circular dependency cycles'

runs:
  using: 'node20'
  main: 'dist/index.js'
